erp.url=http://www.fluxis.com.br:8083/fluxis/login.do
erp.usuario=alexandre.lessa@celer.matriz
erp.senha=0
browser.timeout.default=15
browser.timeout.long=30
browser.headless=false
browser.maximize=true